name: shanesanders
favicon: null
layout_spectrum: 0.75267
typography_spectrum: 0.46809
title: 'Artwork, Design and Experiments by Shane Sanders'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76746039-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d05507'
    - '#731803'
    - '#ffffff'
    - '#de8f07'
    - '#fee814'
  brandStrength: 1
  lightness: 0.9318784265778959
  saturation: 0.7413776889443398
  rhythmicContrast: 0
purpose: []
