typography_spectrum: 0.46809
color:
  brandColors:
    - '#d05507'
    - '#731803'
    - '#ffffff'
    - '#de8f07'
    - '#fee814'
  brandStrength: 1
  lightness: 0.9318784265778959
  saturation: 0.7413776889443398
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.75267
analytics:
  google: UA-76746039-1
  facebook: null
  twitter: null
name: shanesanders
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: 3D Models
    id: 6ab06bff-4d37-43c7-92ae-7f3e102d6dcb
    type: content
favicon: null
title: Experiments
purpose: []
