name: shanesanders
favicon: null
layout_spectrum: 0.49739
typography_spectrum: 0.49363
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d05507'
    - '#731803'
    - '#ffffff'
    - '#de8f07'
    - '#fee814'
  brandStrength: 1
  lightness: 0.9318784265778959
  saturation: 0.7413776889443398
  rhythmicContrast: 0.5
purpose: []
